export const GAME_WIDTH = 640;
export const GAME_HEIGHT = 360;
export const LOGICAL_ASPECT_RATIO = GAME_WIDTH / GAME_HEIGHT;

export const RENDERER_CONFIG = {
  width: GAME_WIDTH,
  height: GAME_HEIGHT,
  resolution: 1,
  autoDensity: false,
  antialias: false,
  backgroundColor: 0x0b1018,
  preference: 'webgl' as const,
};

export const RUNTIME_CONFIG = {
  teacher: {
    startX: 156,
    startY: 298,
    endX: 484,
  },
  probe: {
    duration: 4,
    bobHeight: 6,
    bobDuration: 0.25,
    bobRepeats: 7,
    visualRotation: 0.035,
    panStart: 0.8,
    panDistance: 12,
    shakeStart: 2.65,
    shakeStrength: 4,
    shakeStep: 0.06,
    shakeRepeats: 3,
  },
  speed: {
    min: 0.25,
    max: 2,
    default: 1,
  },
} as const;

export type CitySkyState = 'day' | 'sunset' | 'night';
export type CitySkyMode = 'auto' | CitySkyState;

export const MOVIE_CONFIG = {
  teacher: {
    startX: 390,
    startY: 292,
  },
  classroom: {
    duration: 8,
    entranceDuration: 1.25,
    offscreenLeft: -48,
    offscreenRight: GAME_WIDTH + 48,
    teacherScale:1.2,
    teacherGroundY: 366,
    teachingX: 222,
    putBookDuration: 0.42,
    lessonStartAt: 1.72,
    dialogueLanguageAt: 2.08,
    dialogueLanguageEndAt: 3.42,
    blackboardAt: 3.62,
    blackboardDuration: 0.62,
    talkResumeAt: 4.24,
    lookClockAt: 5.12,
    dialogueEndClassAt: 5.34,
    dialogueEndClassEndAt: 6.02,
    bellAt: 6.12,
    reactionEndAt: 6.48,
    runStartAt: 6.48,
    windowJumpAt: 7.35,
    windowExitAt: 8,
    talkFrameDuration: 0.42,
    sprintFrameDuration: 0.12,
    windowRunX: 510,
    windowExitY: 250,
    jumpHeight: 36,
  },
  city: {
    initialLandingAt: 0.4,
    runSpeed: 60,
    runFrameDuration: 0.12,
    platformYOffset: 80,
    // Rooftop visual decorations are currently disabled in CityScene.
    // rooftopDecorationScale: 0.8,
    roofPadding: 24,
    teacherScale: 0.3,
    parallax: {
      far: { speed: 60, scale: 0.5 },
      mid: { speed: 140, scale: 0.5 },
      front: { speed: 200, scale: 0.5 },
    },
    layout: {
      far: { yRatio: -0.18 },
      mid: { yRatio: 0.00 },
      front: { yRatio: 0.22 },
    },
    sky: {
      cloudSpeed: 8,
      timeline: {
        dayStableEnd: 0.35,
        dayToSunsetEnd: 0.55,
        sunsetStableEnd: 0.65,
        sunsetToNightEnd: 0.85,
      },
      states: {
        day: {
          topColor: 0x4b93d1,
          middleColor: 0x78b8e2,
          horizonColor: 0xb8def0,
          brightness: 1,
          cloudColor: 0xeaf5ff,
          cloudAlpha: 0.42,
          starAlpha: 0,
          moonAlpha: 0,
          windowLightAlpha: 0.1,
          cityBrightness: 1,
          citySaturation: 0,
          cityTint: 0xffffff,
          cityTintStrength: 0,
        },
        sunset: {
          topColor: 0x57468e,
          middleColor: 0x9a5aa4,
          horizonColor: 0xf3a16d,
          brightness: 0.98,
          cloudColor: 0xf0a0ba,
          cloudAlpha: 0.46,
          starAlpha: 0.05,
          moonAlpha: 0,
          windowLightAlpha: 0.45,
          cityBrightness: 0.88,
          citySaturation: 0.05,
          cityTint: 0xffb5a6,
          cityTintStrength: 0.2,
        },
        night: {
          topColor: 0x071637,
          middleColor: 0x142b5d,
          horizonColor: 0x38527a,
          brightness: 0.94,
          cloudColor: 0x3f427d,
          cloudAlpha: 0.5,
          starAlpha: 0.88,
          moonAlpha: 0.96,
          windowLightAlpha: 1,
          cityBrightness: 0.7,
          citySaturation: -0.12,
          cityTint: 0x8aaee9,
          cityTintStrength: 0.24,
        },
      },
    },
    landingSquash: 0.2,
    rooftops: [
      {
        id: 'A',
        height: 100,
        landingX: 48,
        roofY: 264,
        runDuration: 2,
        jumpToNext: { height: 58, duration: 1.05 },
      },
      {
        id: 'B',
        height: 118,
        landingX: 230,
        roofY: 246,
        runDuration: 1,
        jumpToNext: { height: 72, duration: 1.1 },
      },
      {
        id: 'C',
        height: 94,
        landingX: 360,
        roofY: 270,
        runDuration: 3,
      },
    ],
    finalJump: {
      targetX: 530,
      targetY: GAME_HEIGHT + 100,
      height: 42,
      duration: 1.25,
    },
  },
  hallway: {
    duration: 10,
    exitX: GAME_WIDTH + 48,
    exitDuration: 0.9,
    fallStartX: 185,
    fallStartY: -88,
    landingY: 278,
    groundY: 278,
    fallDuration: 0.95,
    landingImpactDuration: 0.14,
    landingShakeStrength: 5,
    rollStartX: 185,
    rollEndX: 312,
    rollStartAt: 1.1,
    rollDuration: 0.75,
    rollFrameDuration: 0.08,
    rollScale: 0.25,
    rollVisualY: -87,
    impactScale: 0.18,
    impactVisualY: -87,
    dustScale: 0.2,
    dustVisualY: -38,
    dustStartScale: 0.9,
    dustEndScale: 1.05,
    residualDustDuration: 0.25,
    rollEndScale: 0.14,
    rollEndPauseDuration: 0.5,
      bookCatchAt: 3.1,
      bookCatchSettleDuration: 0.18,
      walkOutDuration: 3.6,
    endingCardAt: 8.9,
    endingCardDuration: 0.35,
  },
  transition: {
    duration: 0.7,
    flashDuration: 0.1,
  },
  speed: {
    min: 0.25,
    max: 2,
    default: 1,
  },
} as const;
